### PR TITLE
feat: implement quote function in publication contract

### PR DESCRIPTION
**Pull request by EjembiEmmanuel**

### CODE REVIEW

**Comment by codeWhizperer** [comment]
@EjembiEmmanuel Kindly add the test cases for this function

**Comment by EjembiEmmanuel** [comment]
@codeWhizperer working on it

**Comment by EjembiEmmanuel** [comment]
@codeWhizperer I've added tests

**Comment by codeWhizperer** [comment]
@EjembiEmmanuel well-done ser. Kindly emit an event for the `quote` implementation; you can reference mirror as a guide

**Comment by EjembiEmmanuel** [comment]
Okay

**Comment by codeWhizperer** [comment]
> Okay

@EjembiEmmanuel And also, extend the test cases. Test for multiple users quoting a post and also for the root_profile_address and pointed_profile_address. once that's done, PR should be good!

**Comment by EjembiEmmanuel** [comment]
Alright, got it!

**Pull request merged**
