### PR TITLE
Add tests for all events emitted in handle_registry.cairo

### PR DESCRIPTION
**Pull request by EmmanuelAR**
This pr add:
- new test test_emmit_linked_event for HandleLinked event
- new test test_emmit_unlinked_event for HandleUnlinked event
Captura de pantalla 2024-08-03 a la(s) 12 46 23 a  m

### CODE REVIEW

**Comment by EmmanuelAR** [comment]
Ticket #93

**Comment by Darlington02** [comment]
Hello @EmmanuelAR, please run `scarb fmt` to fmt your contracts so the workflow passes

**Comment by EmmanuelAR** [comment]
@Darlington02 done!

**Comment by Darlington02** [comment]
@allcontributors please add @EmmanuelAR for code

**Pull request merged**
