### PR TITLE
Add more follownft tests

### PR DESCRIPTION
**Pull request by od-hunter**

### CODE REVIEW

**Comment by od-hunter** [comment]
Hello, I'm having a bit of trouble testing for  minting and burning can I get some guidance on this?

**Comment by Darlington02** [comment]
Hello @od-hunter what you'd need to do, is simply check that an nft exists for that profile address from the collection after following happens, and the existing nft is burnt after unfollowing.

PS: the follow nft contract is an extension of OZ's ERC721

**Comment by Darlington02** [comment]
Hey @od-hunter great work! just run the `scarb fmt` command so your codes are formatted following the recommended standard.

**Comment by Darlington02** [comment]
@allcontributors add @od-hunter for code

**Pull request merged**
