### PR TITLE
feat: implement mint handle function

### LINKED ISSUE #15: Implement the `mint_handle` function
The `mint_handle` function mints a new karst handle to a profile address.

Takes in the local name, validates it and ties it to the profile address. Here are some resources to help you with implementation:
- [Lens implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/LensHandles.sol)
- [Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:
- Implement the `mint_handle` external and `_mint_handle` private functions respectively
- write the associated test for the implemented function

you are not expected to:
- implement the `_validate_local_name` function, but ensure to call it with the right variable passed in. will be implemented in another issue.

Note that:
- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

### PR DESCRIPTION
**Pull request by kateberryd**
resolves  #15

### CODE REVIEW

**Comment by codeWhizperer** [comment]
@kateberryd Gm, well-done. Kindly add the test for `get_token_id.`

**Comment by kateberryd** [comment]
@codeWhizperer GM. Alright. Thank you

**Comment by codeWhizperer** [comment]
> @codeWhizperer GM. Alright. Thank you 

@kateberryd, we can round this up before the end of the day, right?

**Comment by kateberryd** [comment]
Yeah @codeWhizperer

**Pull request merged**
