### PR TITLE
feat: handle burn

### LINKED ISSUE #16: implement the `burn_handle` function
The `burn_handle` function burns a karst handle token and removes it from associated mappings.

Here are some resources to help you with implementation:

[Lens implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/LensHandles.sol#L121)
[Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:

- Implement the `burn_handle external` function.
- write the associated test for the implemented function

Note that:

- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

### PR DESCRIPTION
**Pull request by Oshioke-Salaki**
Implemented handle_burn function wrote tests for it.

Fixes #16

### CODE REVIEW

**Comment by codeWhizperer** [comment]
@Oshioke-Salaki Gm chief, well done. Could you please look into the test cases. I don't think the implementation is correct. 
There's no declaration and deployment of the Handle contract within the `__setup__`

**Comment by codeWhizperer** [comment]
@Oshioke-Salaki any update on this?

**Comment by Oshioke-Salaki** [comment]
Still working on it

**Comment by codeWhizperer** [comment]
@Oshioke-Salaki well-done ser, please format your code and make a commit, the checks fails.

**Comment by Oshioke-Salaki** [comment]
Please check telegram ser.

**Pull request merged**
